In [1]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\USUARIO\Desktop\vizpro-D3\vizpro\samples\alphabet.csv")

In [3]:
df.head()

  letter  frequency
0      A    0.08167
1      B    0.01492
2      C    0.02782
3      D    0.04253
4      E    0.12702

In [7]:
df_2 = pd.read_csv(r"C:\Users\USUARIO\Desktop\vizpro-D3\vizpro\samples\state-population-2010-2019.tsv", sep="\t")
df_2.head()

          State      2019      2010
0    California  39512223  37254523
1         Texas  28995881  25145561
2       Florida  21477737  18801310
3      New York  19453561  19378102
4  Pennsylvania  12801989  12702379

In [2]:
import statsmodels.api as sm


affairs = sm.datasets.get_rdataset('Affairs', 'AER').data
affairsData = affairs.to_dict(orient='records')
affairs.head()

,affairs,gender,age,yearsmarried,children,religiousness,education,occupation,rating
rownames,,,,,,,,,
4,0,male,37.0,10.00,no,3,18,7,4
5,0,female,27.0,4.00,no,4,14,6,4
11,0,female,32.0,15.00,yes,1,12,1,4
16,0,male,57.0,15.00,yes,5,18,6,5
23,0,male,22.0,0.75,no,2,17,6,3

In [4]:
from vizpro import CustomWidget, MatrixLayout, MatrixCreator
import traitlets

In [5]:

path = "samples/d3_barchar2.js"

class CustomBarplot(CustomWidget):
    _esm = CustomWidget.createWidgetFromLocalFile(paramList=["data", "x", "y", "hue"], filePath=path)
    
    #_esm = CustomWidget.createWidgetFromUrl(paramList=["data", "x", "y", "hue"], jsUrl=url)
    
    data = traitlets.List([]).tag(sync=True)
    x = traitlets.Unicode().tag(sync=True)
    y = traitlets.Unicode().tag(sync=True)
    hue = traitlets.Unicode().tag(sync=True)

barplot = CustomBarplot(data=df.to_dict(orient="records"), x='letter', y='frequency')

In [6]:
barplot

In [ ]:

path = "samples/d3_barchar3.js"

class CustomBarplot(CustomWidget):
    _esm = CustomWidget.createWidgetFromLocalFile(paramList=["data", "x", "y", "hue"], filePath=path)

    data = traitlets.List([]).tag(sync=True)
    x = traitlets.Unicode().tag(sync=True)
    y = traitlets.Unicode().tag(sync=True)
    hue = traitlets.Unicode().tag(sync=True)
barplot2 = CustomBarplot(data=df_2.to_dict(orient="records"), x='State', y='population_2019', hue='region')

In [9]:
barplot2