In [1]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [1]:
#%pip install -e .[dev]

In [2]:
from D3Bridge import CustomWidget, MatrixLayout, MatrixCreator
import D3Bridge as ds
import traitlets

In [3]:

affairs = ds.get_dataset("affairs")
affairs.head()

,rownames,affairs,gender,age,yearsmarried,children,religiousness,education,occupation,rating
0,4,0,male,37.0,10.00,no,3,18,7,4
1,5,0,female,27.0,4.00,no,4,14,6,4
2,11,0,female,32.0,15.00,yes,1,12,1,4
3,16,0,male,57.0,15.00,yes,5,18,6,5
4,23,0,male,22.0,0.75,no,2,17,6,3

In [4]:
import json
path_ = "../datasets/states-albers-10m.json"
mapa_data = json.load(open(path_))

In [5]:
path_map = r"..\samples\map.js"

class CustomMapa(CustomWidget):
    _esm = CustomWidget.createWidgetFromLocalFile(paramList=["data"], filePath=path_map,
                                                  extra_imports=['import * as topojson from "https://esm.sh/topojson-client@3";'])
    data = traitlets.Dict(mapa_data).tag(sync=True)
    selectedValues = traitlets.List([]).tag(sync=True)

    def on_select_values(self, callback):
        self.observe(callback, names=["selectedValues"])
    

map_widget = CustomMapa(data = mapa_data)

In [6]:
map_widget

In [7]:
df_sales = ds.get_dataset("sales")
df_sales.head()

           market          segment  value
0      Auburn, AL    Almond lovers   3840
1      Auburn, AL     Berry buyers   1920
2      Auburn, AL   Carrots-n-more    960
3      Auburn, AL  Delicious-n-new    400
4  Birmingham, AL    Almond lovers   1600

In [8]:
class CustomMariko(CustomWidget):
    _esm = CustomWidget.createWidgetFromLocalFile(paramList=["data"], filePath=r"..\samples\mariko.js")
    data = traitlets.List([]).tag(sync=True)

mariko_widget = CustomMariko(data = df_sales.data)

In [9]:
mariko_widget

In [10]:
from D3Bridge import MatrixCreator

matrix = MatrixCreator(3,5)
matrix

In [11]:
matrix.data

[[1, 2, 2, 3, 3], [1, 4, 4, 4, 4], [1, 5, 5, 5, 5]]

In [12]:
iris = ds.get_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
from D3Bridge import ScatterPlot

scatterplot = ScatterPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=['#1f77b4','#ff7f0e','#2ca02c']
)
scatterplot

In [15]:
from D3Bridge import BarPlot
barplot1 = BarPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=['#1f77b4','#ff7f0e','#2ca02c']
)
barplot1

In [16]:
from D3Bridge import HistogramPlot

histplot = HistogramPlot(
    data=iris.data,
    x="petal_length",
    color= "steelblue" #color_picker.value[0]
)
histplot

In [17]:
from D3Bridge import LinearPlot

lineplot = LinearPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=['#1f77b4','#ff7f0e','#2ca02c']
)
lineplot

In [18]:
from D3Bridge import SwatchesInput
color_picker = SwatchesInput()
color_picker

In [19]:
from D3Bridge import MatrixLayout

layout = MatrixLayout(matrix.data)

layout.add(scatterplot,1)
layout.add(barplot1,2)
layout.add(histplot,3)
layout.add(lineplot,4)

layout