In [2]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [1]:
import D3Bridge as ds

iris = ds.get_dataset("iris")
iris

In [3]:
from D3Bridge import SwatchesInput

In [4]:
color_picker = SwatchesInput()
color_picker

In [5]:
from D3Bridge import RadioInput
r = RadioInput(options=["vertical", "horizontal"], value="vertical")
r

In [6]:
from D3Bridge import BarPlot

chart = BarPlot(
    data=iris.data,
    x="sepal_width",
    y="sepal_length", 
    direction=r.value,  # o "horizontal"
    palette=color_picker.value  # Usar la paleta seleccionada en el color picker
)
chart

In [7]:
r

In [8]:
import traitlets
traitlets.link((color_picker, "value"), (chart, "palette"))
traitlets.link((r, "value"), (chart, "direction"))

In [9]:
import xgboost
import shap
# train XGBoost model
X, y = shap.datasets.adult()
model = xgboost.XGBClassifier(n_estimators=100, max_depth=2).fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X[:1000])

In [10]:
shap_values.values[0]

array([ 0.57542464, -0.22314805,  0.62469046, -0.14136081, -0.05084668,
       -0.76538716,  0.00950744,  0.18914504, -1.64663821, -0.0831908 ,
       -0.13031999,  0.00861055])

In [11]:
from D3Bridge import BeeswarmPlot
beeswarm = BeeswarmPlot(explanation=shap_values[:200])
beeswarm

In [12]:
beeswarm.selected_values

In [13]:
from D3Bridge import DecisionPlot
decisionPlot = DecisionPlot(explanation=shap_values[:20])
decisionPlot

In [14]:
decisionPlot.selected_values

In [15]:
from D3Bridge import HistogramPlot

chart2 = HistogramPlot(
    data=iris.data,
    x="petal_length",
    color= "steelblue" #color_picker.value[0]
)
chart2

In [16]:
from D3Bridge import LinearPlot

chart3 = LinearPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=color_picker.value
)
chart3

In [17]:
chart3.selected_values

In [18]:

df = ds.get_geo_dataset("Brazil")

In [19]:
from D3Bridge import GeoMapPlot
mapa = GeoMapPlot(df,config={"labelProperty": "name"})
mapa

In [21]:
mapa.selected_region

'Paraná'

In [22]:
df_2 = ds.get_geo_dataset("sample")
mapa2 = GeoMapPlot(df_2,config={"labelProperty": "NOMBDEP"})
mapa2

In [23]:
mapa2.selected_region

''

In [24]:
from D3Bridge import ForcePlot
forcePlot = ForcePlot(explanation=shap_values[0])
forcePlot

In [25]:
forcePlot.selected_values

In [26]:
from D3Bridge import datasets as ds
df_gas = ds.get_dataset("gas")

In [27]:
from D3Bridge import HeatmapPlot
df_gas = ds.get_dataset("gas")
pivoted_gas = df_gas._data.pivot(index="country", columns="year", values="price")
heatmap = HeatmapPlot(pivoted_gas)
heatmap

In [28]:
from D3Bridge import RidgelinePlot

ridgeline = RidgelinePlot(
    x_axes=["sepal_length", "sepal_width", "petal_length", "petal_width"],
    data=iris.data,
    bins=60
)
ridgeline

In [29]:
from D3Bridge import ScatterPlot

scatterplot = ScatterPlot(
    data=iris.data,
    x="sepal_width",
    y="sepal_length",
    hue="species",
    palette=color_picker.value
)
scatterplot

In [30]:
scatterplot.selected_values

In [31]:
from D3Bridge import WaterfallPlot
watterfallPlot = WaterfallPlot(explanation=shap_values[0])
watterfallPlot

In [33]:
watterfallPlot.selected_values

   data feature_names    values
0  2174  Capital Gain -1.646638