[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MatiasMaravi/D3Bridge/blob/main/examples/dashboard.ipynb)

In [ ]:
#%pip install D3Bridge --quiet

In [2]:
from D3Bridge import CustomWidget, MatrixLayout, MatrixCreator
import D3Bridge as ds
import traitlets

In [3]:

affairs = ds.get_dataset("affairs")
affairs.head()

,rownames,affairs,gender,age,yearsmarried,children,religiousness,education,occupation,rating
0,4,0,male,37.0,10.00,no,3,18,7,4
1,5,0,female,27.0,4.00,no,4,14,6,4
2,11,0,female,32.0,15.00,yes,1,12,1,4
3,16,0,male,57.0,15.00,yes,5,18,6,5
4,23,0,male,22.0,0.75,no,2,17,6,3

In [ ]:
mapa_data = ds.get_geo_dataset("USA")

class CustomMapa(CustomWidget):
    #_esm = CustomWidget.createWidgetFromLocalFile(paramList=["data"], filePath= r"map.js", extra_imports=['import * as topojson from "https://esm.sh/topojson-client@3";'])
    _esm = CustomWidget.createWidgetFromUrl(paramList=["data"], jsUrl="https://raw.githubusercontent.com/MatiasMaravi/D3Bridge/main/D3Bridge/samples/map.js", extra_imports=['import * as topojson from "https://esm.sh/topojson-client@3";'])
    data = traitlets.Dict(mapa_data).tag(sync=True)
    selectedValues = traitlets.List([]).tag(sync=True)

    def on_select_values(self, callback):
        self.observe(callback, names=["selectedValues"])


map_widget = CustomMapa(data = mapa_data)

c:\Users\USUARIO\Desktop\vizpro-D3\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [17]:
map_widget

In [18]:
df_sales = ds.get_dataset("sales")
df_sales.head()

           market          segment  value
0      Auburn, AL    Almond lovers   3840
1      Auburn, AL     Berry buyers   1920
2      Auburn, AL   Carrots-n-more    960
3      Auburn, AL  Delicious-n-new    400
4  Birmingham, AL    Almond lovers   1600

In [64]:
class CustomMariko(CustomWidget):
    #_esm = CustomWidget.createWidgetFromLocalFile(paramList=["data"], filePath=r"mariko.js")
    _esm = CustomWidget.createWidgetFromUrl(paramList=["data"], jsUrl=r"https://raw.githubusercontent.com/MatiasMaravi/D3Bridge/main/D3Bridge/samples/mariko.js")
    data = traitlets.List([]).tag(sync=True)

mariko_widget = CustomMariko(data = df_sales.data)

c:\Users\USUARIO\Desktop\vizpro-D3\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [65]:
mariko_widget

In [66]:
from D3Bridge import MatrixCreator

matrix = MatrixCreator(3,6)
matrix

In [67]:
matrix.data

[[1, 1, 2, 2, 2, 2], [1, 1, 3, 3, 3, 3], [1, 1, 4, 4, 4, 4]]

In [68]:
iris = ds.get_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [69]:
from D3Bridge import ScatterPlot

scatterplot = ScatterPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=['#1f77b4','#ff7f0e','#2ca02c']
)
scatterplot

In [70]:
from D3Bridge import BarPlot
barplot1 = BarPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=['#1f77b4','#ff7f0e','#2ca02c']
)
barplot1

In [71]:
from D3Bridge import HistogramPlot

histplot = HistogramPlot(
    data=iris.data,
    x="petal_length",
    color= "steelblue" #color_picker.value[0]
)
histplot

In [72]:
from D3Bridge import LinearPlot

lineplot = LinearPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=['#1f77b4','#ff7f0e','#2ca02c']
)
lineplot

In [37]:
from D3Bridge import SwatchesInput
color_picker = SwatchesInput()
color_picker

In [74]:
from D3Bridge import MatrixLayout

layout = MatrixLayout(matrix.data)

layout.add(scatterplot,1)
layout.add(barplot1,2)
layout.add(histplot,3)
layout.add(lineplot,4)

layout