[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MatiasMaravi/D3Bridge/blob/main/examples/graphs.ipynb)

In [3]:
import D3Bridge as ds

iris = ds.get_dataset("iris")
iris

In [4]:
from D3Bridge import SwatchesInput

In [5]:
color_picker = SwatchesInput()
color_picker

In [6]:
from D3Bridge import RadioInput
r = RadioInput(options=["vertical", "horizontal"], value="vertical")
r

In [7]:
from D3Bridge import BarPlot

chart = BarPlot(
    data=iris.data,
    x="sepal_width",
    y="sepal_length", 
    direction=r.value,
    palette=color_picker.value  #Use the value of the color picker as the palette for the bar plot
)
chart

In [8]:
r

In [9]:
import traitlets
traitlets.link((color_picker, "value"), (chart, "palette"))
traitlets.link((r, "value"), (chart, "direction"))

In [10]:
import xgboost
import shap
# train XGBoost model
X, y = shap.datasets.adult()
model = xgboost.XGBClassifier(n_estimators=100, max_depth=2).fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X[:1000])

In [10]:
shap_values.values[0]

array([ 0.57542464, -0.22314805,  0.62469046, -0.14136081, -0.05084668,
       -0.76538716,  0.00950744,  0.18914504, -1.64663821, -0.0831908 ,
       -0.13031999,  0.00861055])

In [11]:
from D3Bridge import BeeswarmPlot
beeswarm = BeeswarmPlot(explanation=shap_values[:200])
beeswarm

In [13]:
beeswarm.selected_values

.values =
array([[ 0.00996254,  0.02336961, -0.00312319, -0.22151415, -1.31514736,
         0.18007765, -0.40127194, -0.16524634, -0.14491879, -0.29672226,
        -0.48569321, -0.87700668]])

.base_values =
array([-2.21275629])

.data =
array([[  39,    4,    4,    4, 1980,    1,    8,   40,    0,    9,   27,
           0]])

In [12]:
from D3Bridge import DecisionPlot
decisionPlot = DecisionPlot(explanation=shap_values[:20])
decisionPlot

In [15]:
decisionPlot.selected_values

In [35]:
from D3Bridge import HistogramPlot

chart2 = HistogramPlot(
    data=iris.data,
    x="petal_length",
    color= "steelblue" #color_picker.value[0]
)
chart2

In [36]:
from D3Bridge import LinearPlot

chart3 = LinearPlot(
    data=iris.data,
    x="sepal_length",
    y="sepal_width",
    hue="species",
    palette=color_picker.value
)
chart3

In [38]:
chart3.selected_values

   sepal_length  sepal_width species  count  id
0           4.3     3.000000  setosa      1   0
1           4.4     3.033333  setosa      3   1

In [39]:

df = ds.get_geo_dataset("Brazil")

In [53]:
from D3Bridge import GeoMapPlot
# The configuration is optional, but it allows you to customize the appearance of the map.
mapa = GeoMapPlot(df,config={"labelProperty": "name", #property in the dataset to use as label
                             "projectionType": "mercator", #projection type to use
                             "hoverFillColor": "orange",# color to use when hovering over a region
                             "strokeColor": "black",# color to use for the stroke of the regions
                             "fillColor": "steelblue", #color to use for the fill of the regions
                             "strokeWidth": 1}) #width of the stroke of the regions
mapa

In [54]:
mapa.selected_region

'Rio Grande do Sul'

In [55]:
df_2 = ds.get_geo_dataset("sample")
mapa2 = GeoMapPlot(df_2,config={"labelProperty": "NOMBDEP"})
mapa2

In [44]:
mapa2.selected_region

'AREQUIPA'

In [56]:
from D3Bridge import ForcePlot
forcePlot = ForcePlot(explanation=shap_values[0])
forcePlot

In [57]:
forcePlot.selected_values

In [58]:
from D3Bridge import datasets as ds
df_gas = ds.get_dataset("gas")

In [59]:
from D3Bridge import HeatmapPlot
df_gas = ds.get_dataset("gas")
pivoted_gas = df_gas._data.pivot(index="country", columns="year", values="price")
heatmap = HeatmapPlot(pivoted_gas)
heatmap

In [64]:
from D3Bridge import RidgelinePlot

ridgeline = RidgelinePlot(
    x_axes=["sepal_length", "sepal_width", "petal_length", "petal_width"],
    data=iris.data,
    bins=60
)
ridgeline

In [65]:
from D3Bridge import ScatterPlot

scatterplot = ScatterPlot(
    data=iris.data,
    x="sepal_width",
    y="sepal_length",
    hue="species",
    palette=color_picker.value
)
scatterplot

In [68]:
scatterplot.selected_values

   sepal_length  sepal_width  petal_length  petal_width species
0           4.5          2.3           1.3          0.3  setosa

In [66]:
from D3Bridge import WaterfallPlot
watterfallPlot = WaterfallPlot(explanation=shap_values[0])
watterfallPlot

In [67]:
watterfallPlot.selected_values