In [1]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

env: ANYWIDGET_HMR=1

In [1]:
#%pip install -e .[dev]

In [1]:
from vizpro import CustomWidget, MatrixLayout, MatrixCreator
import vizpro.datasets as ds
import traitlets

In [2]:
affairs = ds.get_dataset("affairs")
affairs.head()

,rownames,affairs,gender,age,yearsmarried,children,religiousness,education,occupation,rating
0,4,0,male,37.0,10.00,no,3,18,7,4
1,5,0,female,27.0,4.00,no,4,14,6,4
2,11,0,female,32.0,15.00,yes,1,12,1,4
3,16,0,male,57.0,15.00,yes,5,18,6,5
4,23,0,male,22.0,0.75,no,2,17,6,3

In [3]:
import json
path_ = "../datasets/states-albers-10m.json"
mapa_data = json.load(open(path_))

In [4]:
path_map = r"..\samples\map.js"

class CustomMapa(CustomWidget):
    _esm = CustomWidget.createWidgetFromLocalFile(paramList=["data"], filePath=path_map,
                                                  extra_imports=['import * as topojson from "https://esm.sh/topojson-client@3";'])
    data = traitlets.Dict(mapa_data).tag(sync=True)
    selectedValues = traitlets.List([]).tag(sync=True)

    def on_select_values(self, callback):
        self.observe(callback, names=["selectedValues"])
    

map_widget = CustomMapa(data = mapa_data)

In [5]:
map_widget

In [6]:
df_sales = ds.get_dataset("sales")
df_sales.head()

           market          segment  value
0      Auburn, AL    Almond lovers   3840
1      Auburn, AL     Berry buyers   1920
2      Auburn, AL   Carrots-n-more    960
3      Auburn, AL  Delicious-n-new    400
4  Birmingham, AL    Almond lovers   1600

In [7]:
class CustomMariko(CustomWidget):
    _esm = CustomWidget.createWidgetFromLocalFile(paramList=["data"], filePath=r"..\samples\mariko.js")
    data = traitlets.List([]).tag(sync=True)

mariko_widget = CustomMariko(data = df_sales.data)

In [8]:
mariko_widget

In [9]:
from vizpro import MatrixCreator

matrix = MatrixCreator(3,6)
matrix

In [10]:
matrix.data

[[1, 1, 1, 2, 2, 2], [1, 1, 1, 2, 2, 2], [1, 1, 1, 2, 2, 2]]

In [11]:
from vizpro import MatrixLayout

layout = MatrixLayout(matrix.data)

layout.add(map_widget,1)
layout.add(mariko_widget,2)

layout