In [166]:
%load_ext autoreload
%autoreload 2
%env ANYWIDGET_HMR=1

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
env: ANYWIDGET_HMR=1

In [167]:
import vizpro.datasets as ds

iris = ds.get_dataset("iris")
iris

In [168]:
from vizpro import SwatchesInput

In [169]:
color_picker = SwatchesInput()
color_picker

In [170]:
from vizpro import RadioInput
r = RadioInput(options=["vertical", "horizontal"], value="vertical")
r

In [171]:
from vizpro.graphs import BarPlot

chart = BarPlot(
    data=iris.data,
    x="sepal_width",
    y="sepal_length", 
    direction=r.value,  # o "horizontal"
    palette=color_picker.value  # Usar la paleta seleccionada en el color picker
)
chart

In [172]:
r

In [173]:
import traitlets
traitlets.link((color_picker, "value"), (chart, "palette"))
traitlets.link((r, "value"), (chart, "direction"))

In [174]:
import xgboost
import shap
# train XGBoost model
X, y = shap.datasets.adult()
model = xgboost.XGBClassifier(n_estimators=100, max_depth=2).fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X[:1000])

In [175]:
shap_values.values[0]

array([ 0.57542464, -0.22314805,  0.62469046, -0.14136081, -0.05084668,
       -0.76538716,  0.00950744,  0.18914504, -1.64663821, -0.0831908 ,
       -0.13031999,  0.00861055])

In [176]:
from vizpro import BeeswarmPlot
beeswarm = BeeswarmPlot(explanation=shap_values[:200])
beeswarm

In [177]:
beeswarm.selected_values

In [178]:
from vizpro import DecisionPlot
decisionPlot = DecisionPlot(explanation=shap_values[:20])
decisionPlot

In [179]:
decisionPlot.selected_values

In [180]:
from vizpro.graphs import HistogramPlot

chart2 = HistogramPlot(
    data=iris.data,
    x="petal_length",
    color_= "green" #color_picker.value[0]
)
chart2

In [181]:
from vizpro.graphs import LinearPlot

chart3 = LinearPlot(
    data=iris.data,
    x="sepal_length",
    y="petal_length",
    hue="species",
    palette=color_picker.value
)
chart3

In [182]:
chart3.selected_values

In [183]:
%pip install gdown

Requirement already satisfied: gdown in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (5.2.1)
Requirement already satisfied: beautifulsoup4 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from gdown) (4.14.3)
Requirement already satisfied: filelock in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from gdown) (3.24.2)
Requirement already satisfied: requests[socks] in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from gdown) (2.32.5)
Requirement already satisfied: tqdm in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from requests[socks]->gdown) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from requests[socks]->gdown) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from requests[socks]->gdown) (2026.1.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in c:\users\equipo\ciclos\visualizacion\vizpro-d3\.venv\lib\site-packages (from tqdm->gdown) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [184]:
import pandas as pd
import os
import numpy as np
import gdown

In [185]:
output_path = "data/dados_com_endereço.csv"
 
if not os.path.isfile(output_path):
    if not os.path.exists("data"):
        os.makedirs("data")
    file_id = "1KHOOsSLsPmfBR6_3624r-NCYgDtpYBWB"
    gdown.download(f"https://drive.google.com/uc?id={file_id}", output_path, quiet=False)
 
df = pd.read_csv(output_path, encoding='utf-8')

In [186]:
df

,ALUNOS_PORCENTAGEM_Q002_Branca,ALUNOS_PORCENTAGEM_Q002_Preta,ALUNOS_PORCENTAGEM_Q002_Parda,ALUNOS_PORCENTAGEM_Q002_Amarela,ALUNOS_PORCENTAGEM_Q002_Indigena,ALUNOS_PORCENTAGEM_Q002_Nao_Declarado,ALUNOS_PORCENTAGEM_Q002,ALUNOS_PORCENTAGEM_Q003A_Nao_moro_com_mae_madrasta,ALUNOS_PORCENTAGEM_Q003A_Sim_moro_com_mae_madrasta,ALUNOS_PORCENTAGEM_Q003A,...,DIRETOR_PORCENTAGEM_Escola_Privada,DIRETOR_PORCENTAGEM_Regiao_Urbana,DIRETOR_PORCENTAGEM_Regiao_Rural,ID_UF,ID_ESCOLA,CO_CEP,CEP_Formatado,LATITUDE,LONGITUDE,ESTADO
0,-0.181019,0.370310,-0.033433,0.001635,0.032168,0.545716,0.037292,0.032269,0.652719,0.061188,...,0.0,0.0,0.0,11,11024968,76954000.0,76954000,-11.928729,-61.995865,Rondônia
1,-0.728795,0.413723,-0.029554,-0.006442,0.021182,0.575601,-0.005260,0.061088,-0.933414,-0.058104,...,0.0,0.0,0.0,11,11025638,76954000.0,76954000,-11.928729,-61.995865,Rondônia
2,-1.073218,-0.634127,0.016374,-0.010495,-0.060129,0.513057,0.024196,-0.002475,0.541702,-0.003277,...,0.0,0.0,0.0,11,11007168,76876336.0,76876336,-9.933454,-63.029705,Rondônia
3,0.876376,0.196214,-0.010416,0.027593,0.027414,0.471988,-0.127692,0.050145,-1.144981,0.072943,...,0.0,0.0,0.0,11,11007885,76872861.0,76872861,-9.899969,-63.021806,Rondônia
4,-0.183652,0.315411,-0.016556,0.013368,0.030859,0.529906,0.123620,0.065266,0.172062,0.044837,...,0.0,0.0,0.0,11,11007893,76870434.0,76870434,-9.939381,-63.016838,Rondônia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,-1.536799,-0.583662,-0.079528,-0.006353,0.032184,0.269827,-0.291650,0.054689,-0.609229,0.003862,...,0.0,0.0,0.0,17,17003440,77980000.0,77980000,-5.354619,-47.878605,Tocantins
603,-1.651954,0.523563,-0.072903,-0.004729,-0.156653,-0.798976,-0.198341,0.018356,-0.857819,-0.065377,...,0.0,0.0,0.0,17,17025621,77716000.0,77716000,-8.805007,-47.789132,Tocantins
604,-0.475601,-0.282094,0.015729,-0.009186,0.037721,0.590361,-0.210514,-0.127882,-1.312520,-0.000017,...,0.0,0.0,0.0,17,17020875,77565000.0,77565000,-10.862144,-48.916548,Tocantins
605,-1.345452,0.304216,-0.060123,0.125360,0.042397,-0.231131,-0.017059,0.002052,-0.199997,0.025225,...,0.0,0.0,0.0,17,17002753,77885000.0,77885000,-6.444774,-47.668813,Tocantins
606,-1.179359,-0.274080,0.000372,0.003327,-0.016948,-0.764821,-0.351898,-0.059803,-1.091561,0.006707,...,0.0,0.0,0.0,17,17003512,77958000.0,77958000,-6.022244,-47.900479,Tocantins

In [187]:
from vizpro.graphs import MapPlot
mapa = MapPlot(df[['LATITUDE', 'LONGITUDE', 'ESTADO']])

âœ“ Archivo GeoJSON cargado: 27 estados

In [188]:
mapa